# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaraz_features', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colarazuserprofile',
            old_name='level_text',
            new_name='profile_strength_title',
        ),
        migrations.RemoveField(
            model_name='colarazuserprofile',
            name='level_percentage',
        ),
        migrations.AddField(
            model_name='colarazuserprofile',
            name='elgg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colarazuserprofile',
            name='job_title',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AddField(
            model_name='colarazuserprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colarazuserprofile',
            name='profile_strength_color',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='colarazuserprofile',
            name='profile_strength_width',
            field=models.CharField(default='0%', max_length=5),
        ),
    ]
